package diunipisocc.microTOM.parsers;

import java.io.File;
import java.util.List;

/**
 * This interface is designed for classes related to parsing JSON file of service mesh of the application generated by Kiali
 * @author javad Khalili
 *
 * @param <T>
 */
public interface M2MinerJsonParser<T> {
	public List<T> parse(File jsonFile);
}
