package com.diunipisocc.m2;

import java.io.File;
import java.util.Arrays;
import java.util.List;

public class InputValidator {
	
	private boolean mode;
	// uploading all files in the folder
		public List<File> uploadFiles(String folderAddress) {
			File folder = new File(folderAddress);
			if (!(folder.isDirectory())) {
				System.err.print("'" + folderAddress + "'" + " is not a Folder!!!");
				System.exit(0);
			}

			List<File> listOfFiles = Arrays.asList(folder.listFiles());
			if (listOfFiles.isEmpty()) {
				System.err.println("The folder is empty !!!");
				System.exit(0);
			}
			return listOfFiles;
		}

		// Searches the graph data JSON file generated by Kiali
		public File findJSON(List<File> files) {
			File jsonFile = null;
			for (File file : files) {
				if (file.getName().endsWith(".json")) {
					jsonFile = file;
					break;
				}
			}
			if (jsonFile == null) {
				System.err.println("JSON file not found !!!");
				System.exit(0);
			}
			return jsonFile;
		}
		
		// Assigning node refinement strategy
		public void setMode(String[] args) {
			for (String arg : args) {
				if (arg.equals("-i")) {
					this.mode = true;
				}
			}
			
		}
		
		// Checking the node refinement strategy
		public boolean getMode() {
			return this.mode;
		}
}
