package diunipisocc.microTOM.graph;

/**
 * Edge class is designed for parsing edge elements of graph data JSON file generated by Kiali.
 * @author javad khalili
 *
 */
public class Edge {
	private String id;
	private String sourceId;
	private String targetId;
	private String sourceName;
	private String targetName;
	private String t = ""; 			// 't' for timeout
	private String c = ""; 			// 'c' for circuit breaker
	private String d = "d"; 		// 'd' for dynamic discovery

	/**
	 * No argument consructor for Edge class.
	 */
	public Edge() {
	}

	
	public Edge(String id, String sourceId, String targetId) {
		this.id = id;
		this.sourceId = sourceId;
		this.targetId = targetId;

	}
	
	/**
	 * Parameterized constructor for Edge class.
	 * @param id of the edge assigned by Kiali in graph data JSON file.
	 * @param sourceId assigned by Kiali
	 * @param targetId assigned by Kiali
	 * @param sourceName Name of the service that appears as the source for an edge
	 * @param targetName Name of the service that appears as the target for an edge.
	 */
	public Edge(String id, String sourceId, String targetId, String sourceName, String targetName) {
		// super();
		this.id = id;
		this.sourceId = sourceId;
		this.targetId = targetId;
		this.sourceName = sourceName;
		this.targetName = targetName;
	}

	/**
	 * Getter method for dynamic_discovery property of the edge
	 * @return String value "d" if not null.
	 */
	public String getD() {
		return d;
	}

	/**
	 * Setter method for dynamic_discovery property of the edge.
	 * @param d Assigns the dynamic_discovery property to the edge.
	 */
	public void setD(String d) {
		this.d = d;
	}

	/**
	 * Getter for timeout propert of the edge.
	 * @return String value "t" if not null.
	 */
	public String getT() {
		return t;
	}

	/**
	 * Setter for timeout property of the edge.
	 * @param t assigns the timeout property to the edge.
	 */
	public void setT(String t) {
		this.t = t;
	}

	/**
	 * Getter method for circuit_breaker property of the edge.
	 * @return String "c" if not null.
	 */
	public String getC() {
		return c;
	}

	/**
	 * Setter method for circuit_breaker property of the edge.
	 * @param c assigns the circuit_breaker property to the edge.
	 */
	public void setC(String c) {
		this.c = c;
	}

	/**
	 * Getter method for id of edge.
	 * @return String id of the edge.
	 */
	public String getId() {
		return id;
	}

	/**
	 * Setter method for id of the edge.
	 * @param id Assigns the id to the edge.
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Getter method for source id of the edge.
	 * @return String id of source node.
	 */
	public String getSourceId() {
		return sourceId;
	}

	/**
	 * Setter method for source id of the edge.
	 * @param sourceId Assigns the id of source node of an edge.
	 */
	public void setSourceId(String sourceId) {
		this.sourceId = sourceId;
	}

	/**
	 * Getter method for target id of the edge.
	 * @return String id of target node of the edge.
	 */
	public String getTargetId() {
		return targetId;
	}

	/**
	 * Setter method for target id of the edge
	 * @param targetId Assigns the id target node of the edge.
	 */
	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}
	
	/**
	 * Getter method for source name of the edge.
	 * @return String name of source node of the edge.
	 */

	public String getSourceName() {
		return sourceName;
	}
	/**
	 * Setter method for source name of the edge.
	 * @param sourceName Assigns name of source node of the edge.
	 */

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	/**
	 * Getter method for terget name of the edge.
	 * @return String name of the target node of the edge.
	 */
	public String getTargetName() {
		return targetName;
	}

	/**
	 * Setter method for target name of the edge
	 * @param targetName String name of the target node of the edge.
	 */
	public void setTargetName(String targetName) {
		this.targetName = targetName;
	}

	@Override
	public String toString() {
		return "Edge [sourceName=" + sourceName
				+ ", targetName=" + targetName + ", t=" + t + ", c=" + c + ", d=" + d + "]";
	}

	
}
