package diunipisocc.microTOM.graph;

/**
 * JsService designed for parsing node elements of graph data JSON file generated by Kiali.
 * @author javad khalili
 *
 */

public class JsService {
	
	private String id;
	private String serviceName;
	private String nodeType;
	private boolean hasCB; 			// Circuit Breaker . by default "false"
	private boolean hasVS; 			// Virtual Service . by default "false"

	public boolean isHasCB() {
		return hasCB;
	}

	public void setHasCB(boolean hasCB) {
		this.hasCB = hasCB;
	}

	public boolean isHasVS() {
		return hasVS;
	}

	public void setHasVS(boolean hasVS) {
		this.hasVS = hasVS;
	}

	public JsService(){}
	
	/**
	 * Parameterized constructor of JsService class.
	 * @param id The id assigned to a node by Kiali.
	 * @param serviceName The name assigned to node by Kiali
	 * @param nodeType The type assigned to a node by Kiali.
	 */
	
	public JsService(String id, String serviceName , String nodeType) {
		this.id = id;
		this.serviceName = serviceName;
		this.nodeType = nodeType;
	}
		
	/**
	 * Getter method for id of the node.
	 * @return Stirng id of the node.
	 */
	public String getId() {
		return id;
	}
	/**
	 * Setter method of id of the node.
	 * @param id Assigns an id to the node.
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * Getter method for name of the node.
	 * @return String name of the node.
	 */
	public String getServiceName() {
		return serviceName;
	}
	/**
	 * Setter method for name of the node.
	 * @param serviceName Assigns a name to a node.
	 */
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}
	/**
	 * Getter method for type of the node.
	 * @return String type of the node.
	 */
	public String getNodeType() {
		return nodeType;
	}

	/**
	 * Setter method for type of the node.
	 * @param nodeType Assigns the type of the node.
	 */
	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}

	@Override
	public String toString() {
		return "JsService [id=" + id + ", serviceName=" + serviceName + ", nodeType=" + nodeType + ", hasCB=" + hasCB
				+ ", hasVS=" + hasVS + "]";
	}

	
}
